server:
  port: ${PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_TIME}

service:
  secret:
    plazoleta: ${MS_PLAZOLETA_SECRET_KEY}

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  phone-number: ${TWILIO_PHONE_NUMBER}

appDescription: "Plazoleta Mensajeria"
appVersion: "1.0.0"
